"""Remove user from clothes

Revision ID: 0a03a737cce6
Revises: 69fe5865cc98
Create Date: 2024-10-28 14:54:26.233314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a03a737cce6'
down_revision = '69fe5865cc98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothes', schema=None) as batch_op:
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
