"""Add user to clothes

Revision ID: 69fe5865cc98
Revises: 3bc4d8112edf
Create Date: 2024-10-27 13:52:52.389840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69fe5865cc98'
down_revision = '3bc4d8112edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothes', schema=None) as batch_op:
        batch_op.drop_column('user')

    # ### end Alembic commands ###
