"""Add role column to USER table

Revision ID: e01b1383e6e2
Revises: 0a03a737cce6
Create Date: 2024-10-29 15:32:22.662269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e01b1383e6e2'
down_revision = '0a03a737cce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    userrolesenum = postgresql.ENUM('super_admin', 'admin', 'user', name='userrolesenum')
    userrolesenum.create(op.get_bind())

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('super_admin', 'admin', 'user', name='userrolesenum'), nullable=False, server_default='user'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
